server:
  port: 9000
  static-directory: ../web
  data-directory: sampledata
  log-info: false

client:
  node-types:
    storage:
      name: Storage nodes
      host: ^u[a,s]-s
      partition: root
      disks:
        - md0
        - md2
    compute:
      name: Compute nodes
      host: ^u[a,s]-c
      partition: var-lib-nova-instances
      disks:
        - md0
        - md2
    control:
      name: Control
      host: ^u[a,s]-p
      partition: root
      disks:
        - md0
        - md2
    nova:
      name: Nova
      host: ^nova
      partition: root
      disks:
        - md0
        - md2
    swift:
      name: Swift
      host: ^swift
      partition: root
      disks:
        - md0
        - md2
    all-compute:
      name: Compute
      host: ^u[a,s]-c|^nova
    all-storage:
      name: Storage
      host: ^u[a,s]-s|^swift
  heatmap-load:
    - all-storage
    - all-compute
    - control
  aggregate-storage:
    - storage
    - compute
    - control
    - nova
    - swift
  heatmap-storage:
    - storage
    - compute
    - control
    - nova
    - swift